/**
 * @file Types.hpp
 * @brief GL type aliases, lightweight handle structs, and core library concepts.
 *
 * This header defines the primitive building blocks used throughout meta-gl:
 *
 * - `GlGetProcAddressFn` — the function-pointer loader signature accepted by
 *   @ref metagl::Initialize.
 * - Typed handle structs (`ShaderId`, `TextureId`, …) that wrap a single `GLuint`/`GLint`
 *   without owning the underlying GL resource.  Lifetime management is the caller's
 *   responsibility, exactly as with raw `GLuint` names.
 * - Three C++23 concepts: @ref metagl::GlHandle, @ref metagl::GlEnum,
 *   @ref metagl::SpanCompatible.
 * - `using` declarations that import all GL scalar type aliases into the `metagl` namespace.
 */
#pragma once

#ifndef GL_GLES_PROTOTYPES
#define GL_GLES_PROTOTYPES 0
#endif
#include <GLES3/gl32.h>

#include <cassert>
#include <concepts>
#include <limits>
#include <type_traits>

namespace metagl
{
    /**
     * @brief Signature of a platform-specific GL function-pointer loader.
     *
     * @par Loader callback contract (R37)
     *
     * A compliant loader must satisfy all of the following requirements:
     *
     * **Current context:** The loader must be called with a GL context current on
     * the calling thread.  Behaviour is undefined if no context is bound when
     * @ref Initialize is invoked.
     *
     * **Address lifetime:** Returned function pointers are valid for the lifetime
     * of the context for which they were queried.  After context loss, all
     * previously obtained function pointers must be treated as invalid and
     * @ref Initialize must be called again with a new context to reload them.
     *
     * **Function-pointer conversion:** The returned `void*` is used by meta-gl
     * via `reinterpret_cast` to the actual GL function signature.  The platform
     * loader must return a pointer that is safe to convert this way on the target
     * architecture (this is implementation-defined by [conv.ptr] but holds on all
     * supported platforms).
     *
     * **Failure:** A loader may return `nullptr` for any name it does not support.
     * meta-gl treats `nullptr` as "unavailable" and does not call the slot.
     * Returning a non-null, non-callable address for an unsupported name is
     * undefined behaviour from the perspective of this contract.
     *
     * **WGL sentinel rejection:** `wglGetProcAddress` is legal to use as a loader
     * on Windows, but it returns the sentinel values `(void*)1`, `(void*)2`,
     * `(void*)3`, and `(void*)-1` to indicate failure.  Callers using WGL must
     * wrap it to convert those sentinels to `nullptr` before passing the wrapper
     * to @ref Initialize.  Core OpenGL symbols not returned by `wglGetProcAddress`
     * (because they are part of `opengl32.dll`) should be loaded via
     * `GetProcAddress(opengl32_module, name)` as a fallback.
     *
     * **Thread model:** The loader callback is invoked only from within
     * @ref Initialize on the thread that called @ref Initialize.  It is not
     * called concurrently, and it must not itself call any `metagl::` function.
     *
     * Compatible platform implementations (no wrapper needed on most platforms):
     * - `SDL_GL_GetProcAddress` (SDL2)
     * - `glfwGetProcAddress` (GLFW)
     * - `eglGetProcAddress` (EGL / OpenGL ES, Android, Linux)
     * - `glXGetProcAddress` / `glXGetProcAddressARB` (Linux desktop GL)
     * - `emscripten_webgl_get_proc_address` (Emscripten/WebGL — **not** `eglGetProcAddress`)
     * - `wglGetProcAddress` (Windows — requires the WGL sentinel wrapper described above)
     *
     * @param name  Null-terminated GL function name (e.g. `"glDrawArrays"`).
     * @return Pointer to the GL function, or `nullptr` if unavailable.
     */
    using GlGetProcAddressFn = void* (*)(const char* name);

    /**
     * @brief Typed handle for a GL shader object.
     *
     * Wraps the `GLuint` name returned by `glCreateShader`.
     * Does not own the shader; the caller must call `glDeleteShader` when done.
     */
    struct ShaderId        { GLuint value{}; };

    /**
     * @brief Typed handle for a GL program object.
     *
     * Wraps the `GLuint` name returned by `glCreateProgram`.
     * Does not own the program; the caller must call `glDeleteProgram` when done.
     */
    struct ProgramId       { GLuint value{}; };

    /**
     * @brief Typed handle for a GL texture object.
     *
     * Wraps the `GLuint` name generated by `glGenTextures` / `glCreateTextures`.
     * Does not own the texture; the caller must call `glDeleteTextures` when done.
     */
    struct TextureId       { GLuint value{}; };

    /**
     * @brief Typed handle for a GL buffer object.
     *
     * Wraps the `GLuint` name generated by `glGenBuffers` / `glCreateBuffers`.
     * Does not own the buffer; the caller must call `glDeleteBuffers` when done.
     */
    struct BufferId        { GLuint value{}; };

    /**
     * @brief Typed handle for a GL framebuffer object.
     *
     * Wraps the `GLuint` name generated by `glGenFramebuffers` / `glCreateFramebuffers`.
     * Does not own the framebuffer; the caller must call `glDeleteFramebuffers` when done.
     */
    struct FramebufferId   { GLuint value{}; };

    /**
     * @brief Typed handle for a GL renderbuffer object.
     *
     * Wraps the `GLuint` name generated by `glGenRenderbuffers` / `glCreateRenderbuffers`.
     * Does not own the renderbuffer; the caller must call `glDeleteRenderbuffers` when done.
     */
    struct RenderbufferId  { GLuint value{}; };

    /**
     * @brief Typed handle for a GL sampler object.
     *
     * Wraps the `GLuint` name generated by `glGenSamplers` / `glCreateSamplers`.
     * Does not own the sampler; the caller must call `glDeleteSamplers` when done.
     */
    struct SamplerId       { GLuint value{}; };

    /**
     * @brief Typed handle for a GL vertex array object (VAO).
     *
     * Wraps the `GLuint` name generated by `glGenVertexArrays` / `glCreateVertexArrays`.
     * Does not own the VAO; the caller must call `glDeleteVertexArrays` when done.
     */
    struct VertexArrayId   { GLuint value{}; };

    /**
     * @brief Typed handle for a GL query object.
     *
     * Wraps the `GLuint` name generated by `glGenQueries` / `glCreateQueries`.
     * Does not own the query; the caller must call `glDeleteQueries` when done.
     */
    struct QueryId              { GLuint value{}; };

    /**
     * @brief Typed handle for a GL transform feedback object.
     *
     * Wraps the `GLuint` name generated by `glGenTransformFeedbacks` / `glCreateTransformFeedbacks`.
     * Does not own the object; the caller must call `glDeleteTransformFeedbacks` when done.
     */
    struct TransformFeedbackId  { GLuint value{}; };

    /**
     * @brief Typed handle for a GL program pipeline object.
     *
     * Wraps the `GLuint` name generated by `glGenProgramPipelines` / `glCreateProgramPipelines`.
     * Does not own the pipeline; the caller must call `glDeleteProgramPipelines` when done.
     */
    struct ProgramPipelineId    { GLuint value{}; };

    /**
     * @brief Location of a uniform variable within a program object.
     *
     * Wraps the `GLint` returned by `glGetUniformLocation`.
     * The default value `-1` represents an invalid or absent location.
     */
    struct UniformLocation      { GLint  value{-1}; };

    /**
     * @brief Location (index) of a generic vertex attribute within a program object.
     *
     * Wraps the signed `GLint` returned by `glGetAttribLocation`; `-1`
     * represents an inactive or missing attribute. The unsigned constructor
     * keeps vertex-index call sites concise.
     */
    struct AttribLocation
    {
        GLint value{-1};

        constexpr AttribLocation() noexcept = default;
        constexpr explicit AttribLocation(GLint location) noexcept : value(location) {}
        constexpr explicit AttribLocation(GLuint location) noexcept
            : value(static_cast<GLint>(location))
        {
            assert(location <= static_cast<GLuint>(
                std::numeric_limits<GLint>::max()));
        }

        [[nodiscard]] constexpr bool valid() const noexcept { return value >= 0; }
        [[nodiscard]] constexpr explicit operator bool() const noexcept { return valid(); }
    };

    /**
     * @brief Enumeration index used by glGetActiveAttrib.
     *
     * Unlike @ref AttribLocation, this is an ordinal in the program's active
     * attribute list and is never the signed `-1` location sentinel.
     */
    struct ActiveAttribIndex
    {
        GLuint value{};
    };

    /**
     * @brief Index of an image unit used with `glBindImageTexture`.
     *
     * Wraps a `GLuint` image unit binding point index.
     */
    struct ImageUnit            { GLuint value{}; };

    /**
     * @brief Concept satisfied by a lightweight GL wrapper exposing a scalar
     *        `.value` convertible to `GLuint`.
     *
     * All handle structs defined in this header satisfy this concept.
     * It can be used to write generic functions that accept any meta-gl handle type.
     *
     * @tparam T  Type to check; must have a member `value` convertible to `GLuint`.
     *
     * @code
     * static_assert(GlHandle<TextureId>);   // true
     * static_assert(GlHandle<ShaderId>);    // true
     * static_assert(!GlHandle<GLuint>);     // false — raw scalar, not a handle struct
     * @endcode
     */
    template<typename T>
    concept GlHandle = requires(T h) {
        { h.value } -> std::convertible_to<GLuint>;
    };

    template<GlHandle T>
    [[nodiscard]] constexpr bool operator==(T lhs, T rhs) noexcept
    {
        return lhs.value == rhs.value;
    }

    /**
     * @brief Opt-in traits for enum classes that represent GL bit masks.
     *
     * `GLenum` and `GLbitfield` are commonly aliases of the same C++ type, so
     * their underlying type cannot distinguish domains. Enums.hpp explicitly
     * specializes this trait for real bitfield domains.
     */
    template<typename T>
    struct GlBitfieldTraits
    {
        static constexpr bool enabled = false;
        static constexpr GLbitfield all_bits = 0;
    };

    /**
     * @brief Concept satisfied only by explicitly registered GL bitfield enums.
     */
    template<typename T>
    concept GlBitfield =
        std::is_enum_v<T> &&
        GlBitfieldTraits<T>::enabled;

    /**
     * @brief Concept satisfied by non-bitfield `GLenum` enum classes.
     *
     * Used internally to constrain template parameters to typed GL enumerations.
     *
     * @tparam T  Enum type to check.
     *
     * Bitfield domains are excluded through the explicit
     * @ref metagl::GlBitfieldTraits
     * opt-in even when `GLenum` and `GLbitfield` are the same C++ type.
     */
    template<typename T>
    concept GlEnum =
        std::is_enum_v<T> &&
        std::same_as<std::underlying_type_t<T>, GLenum> &&
        !GlBitfield<T>;

    /**
     * @brief Concept satisfied by types safe for use in `std::span<const T>` GL data uploads.
     *
     * Requires trivial copyability and standard layout so the byte representation
     * is well-defined and can be passed directly to GL upload functions such as
     * `glBufferData`, `glTexImage2D`, etc.
     *
     * @tparam T  Type to check.
     *
     * @code
     * static_assert(SpanCompatible<float>);       // true
     * static_assert(SpanCompatible<glm::vec3>);   // true (assuming trivial + standard layout)
     * static_assert(!SpanCompatible<std::string>); // false
     * @endcode
     */
    template<typename T>
    concept SpanCompatible =
        std::is_trivially_copyable_v<T> &&
        std::is_standard_layout_v<T>;

    // -------------------------------------------------------------------------
    // GL scalar type aliases imported into the metagl namespace for convenience.
    // These are identical to the types defined in <GLES3/gl32.h>.
    // -------------------------------------------------------------------------

    using ::GLbitfield;   ///< Unsigned 32-bit bitfield (same underlying type as GLenum on most platforms).
    using ::GLboolean;    ///< Boolean value (`GL_TRUE` / `GL_FALSE`), typically `unsigned char`.
    using ::GLbyte;       ///< Signed 8-bit integer.
    using ::GLchar;       ///< 8-bit character, used for shader source and info-log strings.
    using ::GLclampf;     ///< 32-bit float clamped to [0, 1].
    using ::GLenum;       ///< Unsigned 32-bit enumeration value.
    using ::GLfixed;      ///< Signed 32-bit fixed-point number (16.16 format).
    using ::GLfloat;      ///< 32-bit IEEE 754 floating-point.
    using ::GLhalf;       ///< 16-bit IEEE 754 half-precision floating-point.
    using ::GLint;        ///< Signed 32-bit integer.
    using ::GLint64;      ///< Signed 64-bit integer.
    using ::GLintptr;     ///< Signed integer wide enough to hold a pointer (for buffer offsets).
    using ::GLshort;      ///< Signed 16-bit integer.
    using ::GLsizei;      ///< Non-negative 32-bit integer for sizes and counts.
    using ::GLsizeiptr;   ///< Non-negative integer wide enough to hold a pointer (for buffer sizes).
    using ::GLsync;       ///< Opaque sync object handle (fence sync).
    using ::GLubyte;      ///< Unsigned 8-bit integer.
    using ::GLuint;       ///< Unsigned 32-bit integer; the raw type for most GL object names.
    using ::GLuint64;     ///< Unsigned 64-bit integer.
    using ::GLushort;     ///< Unsigned 16-bit integer.
    using ::GLvoid;       ///< Alias for `void`; used in some GL signatures for historical reasons.
    using ::GLDEBUGPROC;  ///< Callback type for `glDebugMessageCallback` (KHR_debug / ES 3.2).
}
